gamma: 200
beta: 100
pieta: 0.02
hidden_dim: 1024
z_dim: 128
n_clusters: 10
epo: 1000
lr: 1.e-4
lr_c: 1.e-4
eps: 0.05
warmup: 100
save_every: 50
channels: [1, 50]
kernels: [5]
seeds: [1,2,3,4,5,6,7,8,9]
validate_every: 50
experiment_name: cifar10-mcr_knn