gamma: 200
beta: 100
pieta: 0.02
hidden_dim: 12800
z_dim: 100
n_clusters: 2000
epo: 100
lr: 1.e-4
eps: 0.0005
data_dir: ./data/datasets/coil100.mat
warmup: 0
save_every: 50
channels: [1, 50]
kernels: [5]
output_file: ./data/datasets/coil100_dsc_pretrain.pkl
seeds: [42, 1,2,3,4,5,6,7,8,9]
validate_every: 2000